Flow2 page
NyangDoBaeGoPa/Meomullae-Frontend pull request #4
Opened 2023-01-26 11:56 UTC by nyeonaa

## 🔗 References

- Notion Task Board (link):
- Issue (Link)
- Slack (link):
- Others:

## ✔️ Required Self Checklist

- [ ] My code follows the code style of this project.
- [ ] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## ✔️ CheckList

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation

## ⏰ Time Spent

x hours

## 💬 Description

> Add screenshots or recordings

-

## 🚧 Things to Note

-

## 🔃 Related PRs

-

2023-02-07 08:11 UTC, DonghyunKim98 requested changes
landing 만 screen 으로 옮기고 조금의 변화를 줘봤습니다.

1. `component` 폴더에는 **공통 컴포넌트**만 있도록 관리해주세요.
     - 모든 스크린으로부터 하위 컴포넌트를 만들다보면 관리가 되지를 않습니다.
     - 물론 component/common 폴더와 component/page_name 으로 관리할 수 도 있으나, 지금 방향성이 제가 현업에 있을때 더 깔끔한 폴더 구성 방식이었습니다.
2. 최대한 `px`, color hex 값 등을 그대로 쓰지말고 variant 화 시켜주세요.

2023-02-07 08:11 UTC, DonghyunKim98 commented on provider/ui/ui.provider.tsx
> +});
- `fontFamily` 는 아직 디자이너 분이랑 확인이 안된건죠?

2023-02-07 08:11 UTC, DonghyunKim98 commented on components/LogoHeader/logo-header.component.tsx
> +};
- `HeaderLogo` 에서 `LogoHeader` 로 바꿨습니다.
- 앞으로 어떤 헤더가 더 추가될지 모르는데, prefix 를 붙이는 편이 더 네이밍이 적절하다고 생각해요.
- 추후에 유지보수에 따라 `Header` 파일 하나를 놓고 props 로 분기처리 할 수도 있겠죠?

2023-02-07 08:11 UTC, DonghyunKim98 commented on components/LinearProgressWithLabel/linear-progress-with-label.component.tsx
> +  }, []);
- `React.useEffect` 말고 `useEffect` 를 바로 써주세요.

2023-02-07 08:11 UTC, DonghyunKim98 commented on components/LinearProgressWithLabel/linear-progress-with-label.component.tsx
> +  );
- 여기는 tailwind 가 적용이 안되는건가요???

2023-02-07 08:11 UTC, DonghyunKim98 commented on components/LinearProgressWithLabel/linear-progress-with-label.component.tsx
> +        )}%`}</Typography>
- 상수화가 필요합니다.
- props.value 말고 value 를 한번에 가져와주세요.

2023-02-07 08:11 UTC, DonghyunKim98 commented on components/LinearProgressWithLabel/linear-progress-with-label.component.tsx
> +export const LinearProgressWithLabel = (props: LinearProgressProps & { value: number }) => {
- intersection 을 type 으로 쓴걸 외부로 빼서 새로운 타입을 선언해주세요.

2023-02-07 08:11 UTC, DonghyunKim98 commented on components/Modal/modal.component.tsx
> +};
- 여기는 중요하니깐 잘 봐두세요!
- 추후에 `fowardRef` + `useImperativeHandle` 을 이용해서 리팩토링을 할 수도 있습니다.
- 또한 반드시 `Modal` 을 사용해야할까 를 고민해보세요. 당장 MUI 에서 Modal 공식 페이지를 읽다보면 `Dialog`, `Menu`, `Drawer`, `PopOver` 등이 Modal 을 이용한 고차원 컴포넌트로 소개하고 있습니다.

2023-02-07 08:11 UTC, DonghyunKim98 commented on components/SurveyAnswer/survey-answer.component.tsx
> +        답변1
- 최대한 color 값을 그대로 적는 것을 지향하고 MUI 및 tailwind 에서 제공하는 color 값으로 맞춰주세요.
- theme 에서 설정해주시고, 만약 다른 색을 쓴다고 한다면 디자이너와 상의하세요.

2023-02-07 08:18 UTC, nyeonaa commented on provider/ui/ui.provider.tsx
> +});
Inter이랑 Manrope 쓰셨는, 아직 폰트 바꾸는 것까지 못했습니다..!

2023-02-07 08:19 UTC, nyeonaa commented on components/LinearProgressWithLabel/linear-progress-with-label.component.tsx
> +  );
아 이거는 mui 공식문서에 있는 거 그대로 가져와서 그렇고 tailwindcss 적용되는지 확인하도록 하겠습니다!

2023-02-07 08:20 UTC, nyeonaa commented on components/Modal/modal.component.tsx
> +};
헉 넵!! 다른 것도 사용해보겠습니다 👀

2023-02-11 05:32 UTC, DonghyunKim98 requested changes
전반적으로 그래도 어느정도 감은 찾은 것 같아서 다행이야!

PR 을 조금만 더 잘 작성해줬으면 좋겠어. 링크가 중간에 날라가 버려서 이미지도 제대로 못본것도 있어 😥

2023-02-11 05:32 UTC, DonghyunKim98 commented on components/LogoHeader/logo-header.component.tsx
> +        <IconButton aria-label="logo"></IconButton>
- `<IconButton/>` 으로 변경이 가능해보입니다.

2023-02-11 05:32 UTC, DonghyunKim98 commented on components/Modal/modal.component.tsx
> +        }}
- props 에 함수를 선언하기 보다는 따로 네이밍을 붙여서 빼야 유지보수가 편하다고 생각해
```
onClick={handleClickModal}
```
- 그리고 `MUIModal` 에 onClick 이 있어야 정확하지 않나..?
- 완성된 버전을 봤는데 background 를 눌렀을때는 모달이 꺼지지를 않네. 이건 구현되야 한다고 생각해

2023-02-11 05:32 UTC, DonghyunKim98 commented on components/Modal/modal.component.tsx
> +        <Description description={description} />
- 이 부분을 굳이 Component 안에서 또다른 Component 를 선언할 필요가 있는지 모르겠어.
- 조건부 렌더링을 이용하면 되지 않을까??
```
{description && (<Box></Box/>)}
```
이런식으로

2023-02-11 05:32 UTC, DonghyunKim98 commented on components/MuiButton/muibutton.component.tsx
> +  link?: string;
- Color 만 대문자인 이유를 모르겠어
- size, type 등은 반드시 필요한 props 이지 않니?
- size / type 같은 경우에는 string type 을 선언하는게 맞아
```
type: 'contained' | 'outlined'
```
- `MUIButton` 의 Props 의 경우에는 MUI 쪽에서 제공하는게 있지 않니??

2023-02-11 05:32 UTC, DonghyunKim98 commented on components/MuiButton/muibutton.component.tsx
> +        variant={type ? 'contained' : 'outlined'}
- 이런식으로 사용하지 말고 default Props 를 사용하는 게 나을 것 같아.

2023-02-11 05:32 UTC, DonghyunKim98 commented on provider/ui/ui.provider.tsx
> +      //질문
쓸데 없는 주석은 하지말자!

2023-02-11 05:32 UTC, DonghyunKim98 commented on screen/landing/landing.screen.tsx
> +      </head> */}
- 폰트 적용등은 global.css 나 pages/app.tsx 에서 적용해야 next.js 웹 어플리케이션에 적용이 되는 것으로 알아
- 렌딩페이지에서만 폰트를 사용할 것은 아니니깐!

2023-02-11 05:32 UTC, DonghyunKim98 commented on components/MuiButton/muibutton.component.tsx
> +  tail?: string;
- 아 이거 tailwind 의 약자구나
- 그냥 className 으로 그대로 따라가자. 그래야 vscode extention 도 반영이 될거니깐

2023-02-13 01:36 UTC, DonghyunKim98 requested changes

2023-02-13 01:36 UTC, DonghyunKim98 commented on .github/pull_request_template.md
> +
- github pr template 파일을 바꾼 이유가..?

2023-02-13 01:36 UTC, DonghyunKim98 commented on components/Modal/modal.component.tsx
> +            ))}
- 개행을 표시할려면 이게 최선이었나요??
- typography 는 적용이 안되어 있는것 같은데!

2023-02-13 01:36 UTC, DonghyunKim98 commented on components/MuiButton/muibutton.component.tsx
>    link?: string;
- https://stackoverflow.com/questions/56696018/react-material-ui-typescript-inherit-props-from-button-to-add-different-var
- MUIButtonProps 라는게 있는데 이걸 그대로 가져오는게 더 낫지 않을까??

2023-02-13 01:36 UTC, DonghyunKim98 commented on components/MuiButton/muibutton.component.tsx
>    link?: string;
- 버튼을 클릭했을때 onClick 으로 설정을 해야하지 않을까? 버튼을 클릭했을때 특정 링크로만 가도록만 동작하지는 않잖아.

2023-02-13 01:36 UTC, DonghyunKim98 commented on screen/survey/survey.screen.tsx
> +            className="w-11/12 p-5 shadow-md h-15 rounded-main"
- rounded, width 등은 size 로 관리되야하는 props 라고 생각은 하는데, 이를 반영하기 어렵다면 일단 넘어가자

2023-02-13 01:59 UTC, nyeonaa commented on .github/pull_request_template.md
> +
앜ㅋㅋㅋ ㅠㅠㅠ 이거 pr 어떻게 쓰는지 몰라서 이렇게 쓰는건가 하구 바꿨었눈데 안돌려놨었네요 ㅠ 바꿔놓을게요

2023-02-14 02:34 UTC, DonghyunKim98 requested changes

2023-02-14 02:34 UTC, DonghyunKim98 commented on screen/landing/landing.screen.tsx
> +              {Mml}
- 변수명이 정확히 무엇인지 의미가 살지를 않는데,
```
const TitleText = '머물러에 오신 것을 환영합니다.'
```
등으로 가는게 좋지 않을까? (suffix 로 Text 를 붙이자는거야)

2023-02-14 02:34 UTC, DonghyunKim98 commented on screen/landing/landing.screen.tsx
> +            className="w-11/12 p-5 shadow-md md:w-5/12 md:h-40 rounded-main hover:bg-secondary/50"
- hover 에 대한 내용은 모든 버튼에 공통적으로 사용될거라서 `Button` 에 종속되는게 좋을것같아

2023-02-14 02:34 UTC, DonghyunKim98 commented on screen/landing/landing.screen.tsx
> +            sx={{ height: 100 }}
- `href` 말고 onClick 에 대한 method 를 넘겨줘야지! button 을 클릭했을때 항상 어떤 링크로 넘어가는게 아니니깐
- `sx` 에 `className` 도 있으니 정신이 없다는 느낌이 드는데, 설명이 필요할 것 같아.

2023-02-14 02:34 UTC, DonghyunKim98 commented on provider/ui/ui.provider.tsx
> +  }
- 이거 color 에서 primary 가 바로 안잡혀??

2023-02-14 02:34 UTC, DonghyunKim98 commented on components/Button/button.component.tsx
> +        <Box className="text-center">{title && <Box typography={typography}>{title}</Box>}</Box>
- 개행이 좀 필요해 보인다!

2023-02-14 03:21 UTC, DonghyunKim98 approved these changes

2023-02-14 03:21 UTC, merged