Feat/result page
NyangDoBaeGoPa/Meomullae-Frontend pull request #5
Opened 2023-02-10 16:53 UTC by OnlyYellow

## 🔗 References

- Issue (Link):
   - https://ko.reactjs.org/docs/components-and-props.html
   - https://mui.com/material-ui/customization/color/
   - https://jongbeom-dev.tistory.com/128

## ✔️ Required Self Checklist

- [x] My code follows the code style of this project.
- [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## ✔️ CheckList

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation

## ⏰ Time Spent

2 hours
- 들었던 내용을 바탕으로 최대한 반영을 해보고자 개념들을 검색하며 적용을 시키고자 함.
- Header만 우선적으로 수정. 다만, 수정이 필요할 수도 있다고 생각.

## 💬 Description

> Add screenshots or recordings

|수정된 `Header` 모습|
|-----------------------|
|<img src="https://user-images.githubusercontent.com/110537841/218142752-5addd840-ff53-4f04-b0db-7daa4b76a32f.png" width="600">|

## 🚧 Things to Note

- 색상과 관련하여 Theme을 이용하라는 말을 들어 관련 사이트를 검색하며 훑어봄
- 현재 현아가 작성해 놓은 provider 폴더 안의 ui.provider.tsx에서 `const theme = createTheme({생략})` 에 typography가 설정되어 있는 것을 발견
- 추가로 `palette`를 이용해 primary 색상을 설정
   - figma에 설정되어 있는 수정된 primary 색상의 hex 코드를 mui color 사이트에서 대조해본 결과 `deepPurple[700]`과 동일한 색상임을 발견하고 설정
   - secondary 색상이 노란색상이었고, 이와 동일한 hex 코드를 동일한 페이지에서 찾아봤으나 존재하지 않아 디자인 담당인 용성이에게 알림
- 이를 component에 적용하고자 할 때, `UIProvider`로 불러와서 활용가능

---

- 아무런 설정하지 않은 기본 의 경우 body에 margin이 4방향으로 8px씩 적용된다는 것을 발견
- figma에 따르면 header 양쪽으로 여백이 존재
   - 이를 구현하기 위해, Box로 제일 밖을 감싸고 거기에 px-2를 적용
   - 내부에 또 다른 Box를 생성하여 w-full을 적용하여 구현하고자 함
   - 상위의 내용(body의 margin이 8px씩 배정되어 있다는 것)으로 인하여 해당 방법의 경우 오른쪽으로 치우치는 문제 발생
   - 결국 최상위 Box로는 높이만 설정, UIProvider를 선언, 내부에 다른 Box를 생성해 `mx-2`로 결국 margin을 이용하여 문제 해결
   - 해당 방법 말고는 떠오르는 방법이 존재하지 않음.

---

- 로고인 `MML`을 이미지로 땀
   - 폰트의 종류를 추가하기엔 로고에만 사용되는 부분이라 이미지로 따서 적용해도 되겠다고 판단
- 로고 부분만 새로운 component로 만들어 적용
   - `Button`으로 생성

## 🔃 Related PRs

-

2023-02-11 08:26 UTC, DonghyunKim98 requested changes
좀 꼬여서 리뷰해야할 양이 많아 보이는데, 실질적으로 고친것만 리뷰할려고 노력했습니다~

2023-02-11 08:26 UTC, DonghyunKim98 commented on components/FoodRecommendation/food-recommendation.tsx
> +                  </Button>
일단은 이런 부분 넘어갈게요~~ 추후에는 Button 에서 바로 넘겨줘야합니다.

2023-02-11 08:26 UTC, DonghyunKim98 commented on components/LogoHeader/logo-header.component.tsx
> +    <Box component="div" className="flex bg-[#A1C4DD] w-full h-16">
- background color 를 hex 로 표현해야하나요? tailwind 에서 primary 값을 표현할 수는 없나요?

2023-02-11 08:26 UTC, DonghyunKim98 commented on pages/MBTIresult/index.tsx
> +}
- screen 폴더에 따로 빼서 `export default MBTIResultScreen` 만 있게 해주세요.

2023-02-11 08:26 UTC, DonghyunKim98 commented on pages/RecommendReason/index.tsx
> +}
screen 폴더에 따로 빼서 `export default RecommendReason` 만 있게 해주세요.

2023-02-11 10:17 UTC, OnlyYellow commented on components/FoodRecommendation/food-recommendation.tsx
> +                  </Button>
FoodRecommendation 이랑 MBTIresult 부분은 아예 수정을 하지 않은 목요일 날 갖고갔던 부분 그대로입니다. 참고할게요~

2023-02-11 10:18 UTC, OnlyYellow commented on components/LogoHeader/logo-header.component.tsx
> +    <Box component="div" className="flex bg-[#A1C4DD] w-full h-16">
헤더 부분은 새로 폴더를 만들었습니다. Header 폴더와 Logo를 따로 구분하여 새로 만들었습니다.
해당 부분은 pull 해 온 부분으로 삭제를 하지 않은 부분이라 봐도 될거 같아요

2023-02-11 10:20 UTC, OnlyYellow commented on pages/MBTIresult/index.tsx
> +}
넵 확인하겠습니다!

2023-02-11 10:20 UTC, OnlyYellow commented on pages/RecommendReason/index.tsx
> +}
넵 알겠습니다!

2023-02-12 02:10 UTC, DonghyunKim98 commented on components/Header/header.component.tsx
> +      </UIProvider>
- 지금 봤는데 UIProvider 를 Header 안에서 감싸야하는 이유가 있나요?

2023-02-13 08:43 UTC, OnlyYellow commented on components/Header/header.component.tsx
> +      </UIProvider>
그렇네요 그럴 필요가 없었군요. primary 색상 반영하려면 그렇게 해야하는줄 알았는데 필요가 없었습니다. 수정하겠습니다!

2023-02-17 06:20 UTC, merged